import type { CategoryId, ReferralCategory } from "./types";

// ─────────────────────────────────────────────────────────────
// Internal support categories.
// We keep many categories internally for accurate listening, but
// we deliberately DON'T surface all of them to the user as menu
// sections — Waleef should feel like a companion, not a directory.
// ─────────────────────────────────────────────────────────────

export interface CategoryDef {
  id: CategoryId;
  labelAr: string;
  labelEn: string;
  /** Keywords (lowercased) used by the detection engine. */
  keywords: string[];
  /** Default specialist to gently suggest, if any. */
  referral?: ReferralCategory;
}

export const CATEGORIES: CategoryDef[] = [
  {
    id: "overthinking",
    labelAr: "التفكير الزائد",
    labelEn: "Overthinking",
    referral: "psychologist",
    keywords: [
      "أفكر كثير",
      "افكر كثير",
      "تفكير زايد",
      "ما أقدر أوقف تفكيري",
      "عقلي ما يهدأ",
      "أفكاري كثيرة",
      "أسرح",
      "overthink",
      "can't stop thinking",
      "my mind won't stop",
      "racing thoughts",
    ],
  },
  {
    id: "anxiety",
    labelAr: "القلق",
    labelEn: "Anxiety",
    referral: "psychologist",
    keywords: [
      "قلق",
      "قلقان",
      "متوتر",
      "توتر",
      "خايف",
      "خوف",
      "نفسي تضيق",
      "صدري ضايق",
      "قلبي يدق بسرعة",
      "anxious",
      "anxiety",
      "panic",
      "nervous",
      "worried",
      "on edge",
    ],
  },
  {
    id: "burnout",
    labelAr: "الاحتراق الوظيفي",
    labelEn: "Burnout",
    referral: "career_coach",
    keywords: [
      "محترق",
      "احتراق",
      "تعبت من الشغل",
      "الدوام قاتلني",
      "ما عاد أقدر أداوم",
      "مرهق",
      "زهقت من الشغل",
      "burnout",
      "burned out",
      "exhausted from work",
      "drained",
    ],
  },
  {
    id: "social_anxiety",
    labelAr: "الرهاب الاجتماعي",
    labelEn: "Social anxiety",
    referral: "psychologist",
    keywords: [
      "رهاب اجتماعي",
      "أخاف من الناس",
      "أتوتر قدام الناس",
      "ما أقدر أتكلم قدام",
      "أحرج من الناس",
      "social anxiety",
      "scared of people",
      "shy",
      "afraid to speak",
    ],
  },
  {
    id: "addiction",
    labelAr: "السلوكيات الإدمانية",
    labelEn: "Addiction behaviors",
    referral: "addiction_specialist",
    keywords: [
      "مدمن",
      "إدمان",
      "ادمان",
      "تدخين",
      "أدخن",
      "سيجارة",
      "خمر",
      "مخدرات",
      "حشيش",
      "الجوال مدمن",
      "السوشيال",
      "بورن",
      "إباحية",
      "عادة سرية",
      "ما أقدر أبطل",
      "addiction",
      "addicted",
      "smoking",
      "alcohol",
      "drugs",
      "porn",
      "masturbation",
      "phone addiction",
      "can't quit",
    ],
  },
  {
    id: "identity",
    labelAr: "الهوية وضغط المؤثرين",
    labelEn: "Identity & influencer pressure",
    referral: "psychologist",
    keywords: [
      "ما أعرف نفسي",
      "مين أنا",
      "أقارن نفسي",
      "المؤثرين",
      "حياتهم أحسن",
      "أحس نفسي فاشل مقارنة",
      "هويتي",
      "identity",
      "who am i",
      "comparing myself",
      "influencers",
      "everyone is better",
    ],
  },
  {
    id: "body_image",
    labelAr: "تقبّل الشكل",
    labelEn: "Body image",
    referral: "psychologist",
    keywords: [
      "شكلي",
      "ما أحب جسمي",
      "أكره شكلي",
      "وزني",
      "بدين",
      "نحيف",
      "ما أتقبل نفسي",
      "body image",
      "hate my body",
      "my weight",
      "ugly",
    ],
  },
  {
    id: "chronic_illness",
    labelAr: "المرض المزمن والسرطان",
    labelEn: "Chronic illness & cancer",
    referral: "psychologist",
    keywords: [
      "مرض مزمن",
      "سرطان",
      "علاج كيماوي",
      "تعبان من المرض",
      "مريض",
      "مرضي تعبني",
      "chronic illness",
      "cancer",
      "chemo",
      "diagnosis",
      "my illness",
    ],
  },
  {
    id: "elderly",
    labelAr: "كبار السن والتقاعد",
    labelEn: "Elderly & retirement",
    referral: "psychologist",
    keywords: [
      "تقاعدت",
      "التقاعد",
      "كبرت في السن",
      "ولدي ما يزورني",
      "وحيد بعد التقاعد",
      "retirement",
      "retired",
      "getting old",
      "lonely in old age",
    ],
  },
  {
    id: "family",
    labelAr: "خلافات العائلة",
    labelEn: "Family conflict",
    referral: "family_counselor",
    keywords: [
      "أهلي",
      "عائلتي",
      "خلاف مع أهلي",
      "زوجتي",
      "زوجي",
      "طلاق",
      "أمي",
      "أبوي",
      "مشاكل البيت",
      "family",
      "my parents",
      "my wife",
      "my husband",
      "divorce",
      "family conflict",
    ],
  },
  {
    id: "financial",
    labelAr: "ضغوط مالية",
    labelEn: "Financial & investor stress",
    referral: "career_coach",
    keywords: [
      "ديون",
      "فلوس",
      "مديون",
      "خسرت في السوق",
      "الأسهم",
      "استثمار خسران",
      "ضايقة مالية",
      "راتبي ما يكفي",
      "money",
      "debt",
      "lost money",
      "stocks",
      "financial stress",
      "broke",
    ],
  },
  {
    id: "spiritual",
    labelAr: "صراع القيم والروح",
    labelEn: "Spiritual / value conflict",
    referral: "psychologist",
    keywords: [
      "بعدت عن ربي",
      "حاسس بذنب",
      "إيماني ضعف",
      "تايه روحياً",
      "صراع داخلي",
      "قيمي",
      "spiritual",
      "guilt",
      "faith",
      "lost spiritually",
      "values conflict",
    ],
  },
  {
    id: "trauma",
    labelAr: "الصدمات والتنمّر والإيذاء",
    labelEn: "Trauma, bullying & abuse",
    referral: "psychologist",
    keywords: [
      "تنمر",
      "تعرضت لأذى",
      "صدمة",
      "ضربوني",
      "تحرش",
      "إساءة",
      "ذكريات تؤلمني",
      "trauma",
      "bullying",
      "bullied",
      "abuse",
      "harassment",
      "ptsd",
      "flashback",
    ],
  },
];

/** Categories deliberately surfaced to the user as gentle entry points. */
export const PUBLIC_CATEGORY_IDS: CategoryId[] = [
  "overthinking",
  "anxiety",
  "burnout",
];

export function getCategory(id: CategoryId): CategoryDef | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
